### ISSUE TITLE
Question: Running the Database

### ISSUE THREAD

**Issue by 360disrupt** [mattlord/mongo-embedded-sample#1]
I did follow your instructions and I was able to compile it and run the guestbook. I've seen that you build a docker container from it. It would be great if you could describe how to run it (and how to build a docker container out of it) in a way that it runs without the guestbook and listens to a specific port. E.g. after a debian package installation you can run it on a default port:
```
dbPath="/home/pi/app/mongodb_data"
mongod --dbpath "$dbPath" &
```
And store the data in `/home/pi/app/mongodb_data`.

**Comment by mattlord** [comment]
The container was built and pushed this way:
$ git clone https://github.com/mattlord/mongo-embedded-sample.git
$ cd mongo-embedded-sample 
$ sudo docker build -t mattalord/mongo-embedded-sample:armhf .
$ sudo docker push mattalord/mongo-embedded-sample

MongoDB Embedded is a library that you link into your application -- in this case the example iot_guestbook app. You cannot run it as a separate binary and it has no network support. 

Thank you for your interest!

**Comment by 360disrupt** [comment]
Ok thank you, that makes things more clear. 

To build a non embedded version would I just have to change the target to `mongod` instead of `install-embedded-dev` in step 5 of your tutorial (and would I need step 4)?
Or is this a completely different story?

https://github.com/mongodb/mongo/wiki/Build-Mongodb-From-Source#building-with-scons

I never installed it before from scratch, I used this packages:
```
  yes | apt-get install g++ protobuf-compiler libprotobuf-dev libboost-dev curl m4 wget libssl-dev
  yes | apt-get install mongodb-server
```
Is there a difference in the embedded version or why can a newer version be run on the pi than 3.2, Wasn't there this problem with MongoDB and 32bit ARM?

**Comment by mattlord** [comment]
What's your primary goal? Is it e.g. to install and run standard MongoDB 4.0 on Debian 9/Stretch ARM64? I can then help you get there. :-)

**Comment by 360disrupt** [comment]
Yes, I have a RPI3B+ with rasbian stretch. 

My goal is to run a multi container app with a nodejs application in the backend which uses mongodb as a database. Currently, I have all running without docker and an old mongodb I installed with the package above.
This is the setup I would like to get on my rpi. 

```
version: "3"
services:
    watchtower:
        container_name: watchtower
        image: v2tec/watchtower
        env_file:
             - watchtower.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        command: --interval 30
    mongo:
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - '/var/opt/im/docker/mongo/data:/data/db'
            - '/var/opt/im/docker/backup:/data/backup'
        image: mongo
    360disrupt_nodeapp:
        container_name: 360disrupt_nodeapp
        ports:
            - '8080:8080'
        env_file:
            - nodeapp.env
        depends_on:
            - "mongo"
        volumes:
            - '/var/opt/im/docker/logs:/data/logs'
            - '/var/opt/im/docker/backup:/data/backup'
        image: index.docker.io/360disrupt/360disrupt_nodeapp:latest
    360disrupt_gui:
        container_name: 360disrupt_gui
        ports:
           - '80:80'
        depends_on:
           - "360disrupt_core"
        image: index.docker.io/360disrupt/360disrupt_gui:latest
```

I want to expose the port of the mongo container and use it in my node container. I've done this on linux server but I didn't find a mongo 4.0 docker build for arm. Thus I anted to create my own.
